### ISSUE TITLE
Task stuck in "Requested" status. Restarting gvmd don't help

### ISSUE THREAD

**Issue by wisukind** [greenbone/gvmd#1225]
**Environment:**
```
Ubuntu 18.04
Greenbone Vulnerability Manager 9.0.1~git-e250176b-gvmd-9.0
GIT revision e250176b-gvmd-9.0
Manager DB revision 221
gvm@ov-master-eqi:~$ gsad --version
Greenbone Security Assistant 9.0.1~git-9fb2e63cd-gsa-9.0
gvm@ov-master-eqi:~$ openvas --version
OpenVAS 7.0.1
gvm-libs 11.0.1
```

**Issue:**
I have a task currently held into the "Requested" state since several weeks now. Restarting gvmd & rebooting the system doesn't help, and since Requested tasks cannot be stopped; I am stuck with a task which cannot be run / modified whatsoever. No particular error was logged.  Everything else works as expected, and I my other tasks are working fine.

**How to Reproduce:**
I have no idea unfortunately, as this issue arised without particular reason. I can however help debugging it, as this task is still in Requested state.

**Comment by HulakaSr** [comment]
**gsad --version**
Greenbone Security Assistant 20.08.0~git-fdd51705e-gsa-20.08
**gvmd --version**
Greenbone Vulnerability Manager 20.08.0~git-97bdbeeb-gvmd-20.08
GIT revision 97bdbeeb-gvmd-20.08
Manager DB revision 233
Copyright (C) 2010-2020 Greenbone Networks GmbH
License: AGPL-3.0-or-later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**openvas --version**
OpenVAS 20.8.0
gvm-libs 20.8.0~git-e335110-gvm-libs-20.08
Most new code since 2005: (C) 2020 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


These are the versions I am currently using. I will update them to 20.08.1 and hope this fixes the issue.

**Comment by wisukind** [comment]
Also make sure you are compiling with PostGresql 11 librairies. I have had many problems related to this when using postgresql librairires from version 12 and 13. With PSQL 11, much less problems.

**Comment by y0urself** [comment]
@wisukind @HulakaSr does this still appear? If yes, please create a new issue.
