### ISSUE TITLE
[20.8.1] gvmd vaccum fails

### ISSUE THREAD

**Issue by pomac303** [greenbone/gvmd#1432]
MIght be related to:
https://github.com/greenbone/gsa/issues/2768

md   main:MESSAGE:2021-03-02 09h55.00 utc:43810:    Greenbone Vulnerability Manager version 20.08.1 (DB revision 233)
md manage:   INFO:2021-03-02 09h55.00 utc:43810:    Optimizing: vacuum.
md manage:WARNING:2021-03-02 09h55.01 utc:43810: manage_optimize: failed to stat database: Bad address
md manage:WARNING:2021-03-02 09h55.01 utc:43810: manage_optimize: failed to stat database: Bad address
Optimized: vacuum.
md manage:MESSAGE:2021-03-02 09h55.01 utc:43810:    Optimized: vacuum.

**Comment by cfi-gb** [comment]
Have you verified that you are running the command with the correct user (the one running `gvmd` / having the access permissions to the PostgreSQL database)?

**Comment by pomac303** [comment]
Yes, the same command ran for 41 minutes - it does clear data but something goes wrong - somehow the database has ended up in a 'inconsistent state', but there doesn't seem to be anything i can do to fix it - not even trying to clear out old reports.

**Comment by timopollmeier** [comment]
The "failed to stat database" warnings should only affect the file size comparison, not the vacuum command itself.

As for the inconsistent state: Can you describe what is wrong and check the gvmd log for other warnings?
If you are getting the same error as in greenbone/gsa#2768, have you checked if the report formats are accessible? Since GVM 20.08 the report formats are no longer pre-installed but supplied via a gvmd-data feed.
I think it's unlikely that this is related to the vacuum command but if there is some database corruption, there should be more warnings about failed SQL commands.

**Comment by pomac303** [comment]
Yeah I tought it was a inconsistent state since i couldn't see the reports - turns out that it seems to be a error in the webui fixed in 20.8.6 - haven't tested to confirm yet though

**Comment by cfi-gb** [comment]
Closing as #1447 has been merged just a few minutes ago. Thanks for your report :+1:
