### ISSUE TITLE
Where report broken nasl feeds?

### ISSUE THREAD

**Issue by Dexus** [greenbone/gvmd#1667]
```
lib  nasl:MESSAGE:2021-08-12 20h51.49 utc:245: [245]()(/var/lib/openvas/plugins/2012/secpod_apache_http_srv_cookie_info_disc_vuln.nasl:0) Line 93: Cannot compile regex: Cookie: c[0-9]=X{820}; path=/; (error 10: Invalid contents of {})
```

**Comment by bjoernricks** [comment]
The team responsible for the nasl scripts can be contacted at https://community.greenbone.net/c/vulnerability-tests/7 Therefore it is best to create a new topic there.

@cfi-gb correct me if that is wrong

**Comment by cfi-gb** [comment]
@bjoernricks In general this would be correct, yes.

Not sure about this specific case because the regex is absolutely fine / valid (a malformed regex would never pass the Feed-QA) as we can see here:

https://regexper.com/#Cookie%3A%20c%5B0-9%5D%3DX%7B820%7D

This looks more like an issue / limitation in the underlying regex library of the specific system hosting the scanner as the regex is also absolutely fine when running on a reference system (Debian):

```
res = "Cookie: c1=" + crap(data:"X", length:820) + "; path=/;";
if(res =~ "Cookie: c[0-9]=X{820}; path=/;") {
  display("match");
} else {
  display("no match");
}
```

Output (without any errors):

```
lib  nasl-Message: 10:23:14.085: match
```

**Comment by bjoernricks** [comment]
thanks @cfi-gb for taking care!

@Dexus this is an issue with the regex library on Alpine.

**Comment by Dexus** [comment]
thx

**Comment by cfi-gb** [comment]
@Dexus Forgot to mention:

Third party patches are still welcome (posted at https://community.greenbone.net/c/vulnerability-tests/7) to work around this limitation on the regex library side while keeping compatibility with default systems.

**Comment by bjoernricks** [comment]
Of course. Closing this ticket doesn't mean we aren't open for contributions. It just did mean it is not something we are going to address in `gvmd`.
