### ISSUE TITLE
[7.0.2] Unable to login without the "help" permission

### ISSUE THREAD

**Issue by tuxmaster** [greenbone/gvmd#26]
When an user don't  have the "help" right, the he can't log in any more.

Steps to Reproduce:
- remove the help right for the user
- let the user log in.

Actual results:
Log in impossible

Expected results:
That the user can use the manager, but without the help menu.

**Comment by timopollmeier** [comment]
I assume you mean that logging in to GSA does not work. This happens because the help command is required to check which other commands the user has access to. 

On the one hand, this is an issue with GSA, which should be more explicit about this requirement. On the other hand, for newer manager versions we should probably consider a way for users to get the available commands without permissions.
