### ISSUE TITLE
Schedule: planned schedule doesnt' start - errors in gvmd.log

### ISSUE THREAD

**Issue by pyron83** [greenbone/gvmd#317]
Expected behavior

After creating a schedule (I tried daily and weekly schedules), and configuring it in the desired Task, the Task is expected to run at the expected time configured in the Schedule.

Current behavior

I tried with various settings and tasks, but I've never been able to get the schedule triggered.
Running the task manually instead has no issues and the task runs regularly.

Steps to reproduce

    create or edit a Schedule under "Configuration>Schedules".
    in the Schedule settings, select a desired time and period (eg: Daily) then press the Save button.
    Wait for the Scheduled time and then look if any task with the desired Schedule settings runs or not.

GVM versions

gsa: (gsad --version)
Greenbone Security Assistant 8.0+beta3
GIT revision 41af14bbe-master

gvm: (gvmd --version)
Greenbone Vulnerability Manager 8.0+beta2
GIT revision c4ea8a5-master

openvas-scanner: (openvassd --version)
OpenVAS Scanner 6.0+beta3
GIT revision 19a27e3-master

gvm-libs:
gvm-libs 1.0+beta2 (2018-12-04)

openvas-smb:
openvas-smb 1.0.4 (2018-08-29)
Environment

Operating system:
Ubuntu Server 18.04 x64

Installation method / source: (packages, source installation)
source installation from github repositories

Logfiles

this issue doesn't get reported in the logs (even after the desired time of the schedule, I didn't see anything coming in my "tail -f -n100 /usr/local/var/log/gvm/gvmd.log" - it looks like the Schedule gets totally ignored)

**Comment by tsanchez88** [comment]
I have noticed a similar issue with Schedules failing, but have seen the following errors repeated in the gvmd.log file when the task tries to kick off:

md    gmp:WARNING:2018-12-28 16h52.33 utc:8400: Authentication failure for 'admin' from unix_socket
md manage:WARNING:2018-12-28 16h52.33 utc:8399: scheduled_task_start: gmp_authenticate failed
md manage:WARNING:2018-12-28 16h52.33 utc:8389: scheduled_task_start: child failed


 gsad --version
Greenbone Security Assistant 8.0+beta3
Copyright (C) 2010-2016 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

gvmd --version
Greenbone Vulnerability Manager 8.0+beta2
Manager DB revision 200
Copyright (C) 2010-2017 Greenbone Networks GmbH
License GPLv2+: GNU GPL version 2 or later
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

openvassd --version
OpenVAS Scanner 6.0+beta2
Most new code since 2005: (C) 2018 Greenbone Networks GmbH
Nessus origin: (C) 2004 Renaud Deraison <deraison@nessus.org>
License GPLv2: GNU GPL version 2
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic

**Comment by pyron83** [comment]
> I have noticed a similar issue with Schedules failing, but have seen the following errors repeated in the gvmd.log file when the task tries to kick off:


you're right, I've similar logs:
`md    gmp:WARNING:2019-01-04 10h01.11 utc:20149: Authentication failure for 'admin' from unix_socket
md manage:WARNING:2019-01-04 10h01.11 utc:20148: scheduled_task_start: gmp_authenticate failed
md manage:WARNING:2019-01-04 10h01.11 utc:20143: scheduled_task_start: child failed
md manage:WARNING:2019-01-04 10h01.11 utc:20143: reschedule_task: rescheduling task '007c7e7f-3429-465f-bd04-5dda050c6308'
md manage:MESSAGE:2019-01-04 10h01.21 utc:20159: No CERT database found
md manage:   INFO:2019-01-04 10h01.21 utc:20158: sync_cert: Updating data from feed
md manage:WARNING:2019-01-04 10h01.21 utc:20158: sql_prepare_internal: sqlite3_prepare failed: no such table: cert.dfn_cert_advs
md manage:WARNING:2019-01-04 10h01.21 utc:20158: sql_x_internal: sql_prepare failed
`

**Comment by mattmundell** [comment]
This is possibly solved by greenbone/gvmd/pull/338 where the Start Task alert authentication
was failing.  The Start Task alert and the schedules use the same authentication mechanism.

**Comment by pyron83** [comment]
I'll test that build asap, I've built a Debian test VM on this purpose. I'll update the thread as soon I update the git source on my machine. Thanks.

**Comment by mattmundell** [comment]
Great, thank you.
