### ISSUE TITLE
/build/doc/gmp.rnc not suitable for autogenerating XML classes

### ISSUE THREAD

**Issue by ghost** [greenbone/gvmd#541]
The RNC file /build/doc/gmp.rnc is ok when used for documentation purposes only, but when it is used to autogenerate XML classes (e.g. in Java) for communication with gvmd it has several issues.

- element ERROR undefined
- element sources undefined
- get_filters_response_filters is defined twice
- create_report's element report contains sub-element report. This is allowed following XML standards, but in generated classes it causes an issue, as sub-classes are not allowed to have the same name.
- get_nvts_response_nvt contains element nvt and sub-element get_nvts_response_nvt_preferences_preference_nvt contains element nvt again. Same problem with sub-classes as in create_report.

not sure about this:
- 'filter_keywords = element filter_keywords' should be 'filter_keywords = element keywords'

not an issue but as enhancement:
boolean should be defined as xsd:token { pattern = "yes|no|unknown" }

**Comment by mattmundell** [comment]
Interesting that you're using the RNC.  I have the feeling that nobody has used it in
a long time.  We are actually currently discussing dropping the RNC, in order to
simplify our documentation.

**Comment by wkrane-e2s** [comment]
From my point of view a formal description like RNC is better than any kind of free text documentation.
And isn't RNC the shortest form to create an **exact** description of the XML communication? Anything else e.g. XSD is more complicated.

**Comment by mattmundell** [comment]
Our RNC and our free form HTML doc are generated from an XML format that is part
of the GMP HELP command.  This adds maintenance overhead so I've been
advocating dropping it all in favour of a simple Markdown document.

I don't think RNC (or XSD) is good enough to describe the entire protocol, because
it's not an XML documents (it's a query-response protocol), so there are things
that need to be described like "if this element is present then this other element
can only have these values" and "this is the error response to this".

We receive lots of feedback about our docs being incomplete or lagging behind the
implementation, and this is partly because they're in this complex format.
I'm very keen to switch to something simpler, but perhaps we need to rethink that,
if there are others like you out there.
