### ISSUE TITLE
Configurable PostgreSQL connection details

### ISSUE THREAD

**Issue by alexxq1** [greenbone/gvmd#669]
Currently, the only way to connect to PostgreSQL is the Unix socket at `/var/run/postgresql/.s.PGSQL.5432`

Sometimes, this isn't desired, as the Postgres server might be on a different host, or in a container, or even just a different file socket location.

Could a configuration option be added to change the location of the Postgres connection?

**Comment by romanprocopie** [comment]
PGHOST=/<path shared across contsiners>/ gvmd --create-user admin --password=.....

the actual socket file name is .s.PGSQL.5432, that seems hardcoded and added automatically. 

Just make sure you get the owner right, the UID and GID must be the same across all containers. otherwise it doesn't see the socket file
